# Development Configuration for IRA Workflow Builder

app:
  name: "IRA Workflow Builder"
  version: "0.1.0"
  environment: "development"
  debug: true

api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  log_level: "debug"

cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

storage:
  data_dir: "./data"
  uploads_dir: "./data/uploads"
  outputs_dir: "./data/outputs"
  temp_dir: "./data/temp"
  checkpoints_dir: "./storage/checkpoints"
  conversations_dir: "./storage/conversations"
  metadata_dir: "./storage/metadata"

workflow:
  max_questions: 10
  max_code_execution_time: 120
  max_file_size_mb: 100
  allowed_extensions:
    - ".csv"
    - ".xlsx"
    - ".xls"

logging:
  level: "DEBUG"
  format: "pretty"
  file: "./logs/ira.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

agents:
  planner:
    model: "gpt-4o"
    temperature: 0.7
    max_tokens: 4096
  coder:
    model: "gpt-4o"
    temperature: 0.3
    max_tokens: 4096

observability:
  tracing_enabled: true
  tracing_level: "framework"
  metrics_enabled: true

features:
  checkpointing: true
  conversation_history: true
  code_sandbox: true
  workflow_analytics: false
