# Production Configuration for IRA Workflow Builder

app:
  name: "IRA Workflow Builder"
  version: "0.1.0"
  environment: "production"
  debug: false

api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4
  log_level: "info"

cors:
  origins:
    - "https://your-production-domain.com"
  allow_credentials: true
  allow_methods: ["GET", "POST", "PUT", "DELETE"]
  allow_headers: ["*"]

storage:
  data_dir: "/var/data/ira"
  uploads_dir: "/var/data/ira/uploads"
  outputs_dir: "/var/data/ira/outputs"
  temp_dir: "/tmp/ira"
  checkpoints_dir: "/var/storage/ira/checkpoints"
  conversations_dir: "/var/storage/ira/conversations"
  metadata_dir: "/var/storage/ira/metadata"

workflow:
  max_questions: 10
  max_code_execution_time: 120
  max_file_size_mb: 100
  allowed_extensions:
    - ".csv"
    - ".xlsx"
    - ".xls"

logging:
  level: "INFO"
  format: "json"
  file: "/var/log/ira/ira.log"
  max_bytes: 52428800  # 50MB
  backup_count: 10

agents:
  planner:
    model: "gpt-4o"
    temperature: 0.7
    max_tokens: 4096
  coder:
    model: "gpt-4o"
    temperature: 0.3
    max_tokens: 4096

observability:
  tracing_enabled: true
  tracing_level: "workflow"
  metrics_enabled: true

rate_limiting:
  enabled: true
  per_minute: 60
  per_hour: 1000

features:
  checkpointing: true
  conversation_history: true
  code_sandbox: true
  workflow_analytics: true
